/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sixto.pdfcli;

import java.util.concurrent.Callable;
import picocli.CommandLine;
import picocli.CommandLine.Command;

@Command(
  name = "pdfcli",
  description = "Says hello",
  version = "hello 0.1.0",
  mixinStandardHelpOptions = true
)
public class App implements Callable<Integer> {

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }

    @Override
    public Integer call() throws Exception { // your business logic goes here...
        System.out.println(getGreeting());
        return 0;
    }

    public String getGreeting() {
        return "Hello CLI :)";
    }
}
